eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 10003
spring:
  application:
    name: eurekaclient1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
    #监控统计拦截的filters
    filters: stat
    driver-class-name: com.mysql.jdbc.Driver
    #基本属性
    url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3600ms #超时时间
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接 默认8
        max-wait: -1ms #默认-1 最大连接阻塞等待时间
        min-idle: 0 #最小空闲连接
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
hystrix:
  metrics:
    enabled: true

#filters:
## 熔断降级配置
#- name: Hystrix
#  args:
#    name : default
#    fallbackUri: 'forward:/defaultfallback'
#
## hystrix 信号量隔离，3秒后自动超时
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE
#          thread:
#            timeoutInMilliseconds: 3000
#  shareSecurityContext: true